# Generated by Django 3.0.6 on 2020-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('registration_type', models.IntegerField()),
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('group_id', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
