# Generated by Django 3.0.6 on 2020-05-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200515_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user_id',
            new_name='idcard',
        ),
    ]
