# Generated by Django 3.0.6 on 2020-05-24 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200524_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='confirm_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
