# Generated by Django 3.0.6 on 2020-06-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_login_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fullname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.TextField(max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='eventId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='registration.Event'),
            preserve_default=False,
        ),
    ]
