# Generated by Django 3.0.6 on 2020-06-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200604_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='registration_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
